### ISSUE TITLE
Use a Conda `environment.yml` file to specify as many dependencies as possible

### ISSUE THREAD

**Issue by lbianchi-lbl** [watertap-org/watertap-ui#13]
**DISCLAIMER**: Please feel free to disregard if this is not useful at this time.

I was thinking that having a minimal Conda env file in this repository could allow us to make the installation procedure more streamlined and robust (i.e. lowering the chance that the multi-step and -language results in a non-working environment):

- Conda is not Python specific, so it should be possible to specify a known working version of the packages needed to bootstrap the JS/Electron environment (e.g. NPM, as part of the [nodejs package](https://anaconda.org/conda-forge/nodejs)) together with the backend dependencies
- Additionally, we would be able to specify the Python version as well: I don't think this is a huge problem for WaterTAP itself, but better safe than sorry, i.e., once we know that everything works with Python 3.9, we can just specify `python=3.9` in the Conda env file and reduce the possibility that whatever unknown version of Python present in the installation environment will be used

Creating a Conda `environment.yml` file is straightforward and could look e.g. like this:

```yml
name: watertap-ui-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - nodejs=17.9.0
  - pip
  - pip:
    - -r requirements.txt  # install backend dependencies specified in this repo
    - watertap @ https://github.com/watertap-org/watertap/archive/workshop_tutorial.zip  # or any other branch/commit that's known to be working
```

And then, once `conda` is installed through e.g. Miniconda, the installation could be as simple as:

```sh
conda env create -f environment.yml && conda activate watertap-ui-env
(cd electron/ ; npm install) && (cd electron/ui/ ; npm install)
```

Let me know if this something that you think could be useful, and I'd be happy to help set this up and test it.
